server:
  port: 8081
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: employee
          uri: lb://emp-server
          predicates:
            - Path=/api_emp/**
          filters:
            - StripPrefix=1
        - id: customer
          uri: lb://customer-server
          predicates:
            - Path=/api_cust/**
          filters:
            - StripPrefix=1
