logging:
  level:
   com.ling.manager: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/consumer_relation_project?useSSL=false&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 10
        max-wait: 100
    password: abc123456
mybatis-plus:
  type-aliases-package: com.ling.employee.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

